feat: adding scalafix

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,6 +1,18 @@
 #!/bin/sh
+EXIT=0
+
 sbt scalafmtCheck
 if [ $? -ne 0 ]; then
-  echo "Code is not formatted. Run 'sbt scalafmt' and try again."
-  exit 1
+  echo ""
+  echo "[FAIL] scalafmt: Code is not formatted. Run 'sbt scalafmt' to fix."
+  EXIT=1
 fi
+
+sbt "scalafixAll --check"
+if [ $? -ne 0 ]; then
+  echo ""
+  echo "[FAIL] scalafix: Linting issues found. Run 'sbt scalafixAll' to fix."
+  EXIT=1
+fi
+
+exit $EXIT
